# Generated by Django 5.0.7 on 2024-08-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_job_description_alter_job_slug_alter_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacancies.specification'),
        ),
    ]
