# Generated by Django 5.0.7 on 2024-08-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_specification_job_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.specification'),
        ),
    ]
