# Generated by Django 5.0.7 on 2024-08-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_experience_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='vacancies.experience'),
        ),
    ]
