# Generated by Django 5.1 on 2024-08-12 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_remove_job_tags_job_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.specification', verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='vacancies.experience', verbose_name='Опыт работы'),
        ),
    ]
